name = "uniswap-v3"
description = "Decentralized trading protocol"
version = "0.0.1"

[setting.salt]
defaultValue = "uniswap"

[setting.token0_address]
defaultValue = "0x0000000000000000000000000000000000000000"

[setting.token1_address]
defaultValue = "0x0000000000000000000000000000000000000000"

[setting.initialize_ratio]
defaultValue = "79228162514264337593543950336"

[setting.pool_fee]
defaultValue = 500

[contract.weth]
artifact = "WETH9"
step = 1

# [contract.library]
# artifact = "NFTDescriptor"
# step = 1

[contract.factory]
artifact = "UniswapV3Factory"
salt = "<%= settings.salt %>"
step = 1

# [contract.position_descriptor]
# artifact = "NonfungibleTokenPositionDescriptor"
# salt = "<%= settings.salt %>"
# args = [
#   "<%= outputs.self.contracts.weth.address %>",
#   "weth9",
# ]
# step = 2

# [contract.position_manager]
# artifact = "NonfungiblePositionManager"
# salt = "<%= settings.salt %>"
# args = [
#   "<%= outputs.self.contracts.factory.address %>",
#   "<%= outputs.self.contracts.weth.address %>",
# ]
# step = 3

[contract.router]
artifact = "SwapRouter"
salt = "<%= settings.salt %>"
args = [
  "<%= outputs.self.contracts.factory.address %>",
  "<%= outputs.self.contracts.weth.address %>",
]
step = 3

[invoke.createPool]
addresses = ["<%= outputs.self.contracts.factory.address %>"]
abi = "<%= outputs.self.contracts.factory.abi %>"
func = "createPool"
args = [
  "<%= settings.token0_address %>",
  "<%= settings.token1_address %>",
  "<%= settings.pool_fee %>"
]
step = 4

[invoke.initialize]
addresses = ["<%= outputs.self.invokes.createPool.events.0.PoolCreated.0.args.4 %>"]
abi = "<%= outputs.self.contracts.factory.abi %>"
func = "initialize"
args = [
  "<%= settings.token0_address %>",
]
step = 5
