name = "@uniswap/v3-core"
description = "Decentralized trading protocol"

[setting.salt]
defaultValue = "uniswap"

[contract.factory]
artifact = "UniswapV3Factory"
salt = "<%= settings.salt %>"
step = 1

[contract.sUSD]
artifact = "ERC20"
args = ["Synthetix USD", "sUSD"]
salt = "sUSD"
step = 1

[contract.USDC]
artifact = "ERC20"
args = ["USDC", "USDC"]
salt = "USDC"
step = 1

[invoke.createPool]
address = "<%= outputs.factory.contracts.UniswapV3Factory.address %>"
abi = "<%= outputs.factory.contracts.UniswapV3Factory.abi %>"
func = "createPool"
args = ["USDC", "sUSD", 0]
step = 2
