name = "@uniswap/v3-core"
description = "Decentralized trading protocol"

[setting.salt]
defaultValue = "uniswap"

[setting.token0_name]
defaultValue = "Synthetix USD"

[setting.token0_symbol]
defaultValue = "sUSD"

[setting.token1_name]
defaultValue = "USD Coin"

[setting.token1_symbol]
defaultValue = "USDC"

[contract.UniswapV3Factory]
artifact = "UniswapV3Factory"
salt = "<%= settings.salt %>"
step = 1

[import.token0]
source = "erc20:0.0.1"
args = ["<%= settings.token0_name %>", "<%= settings.token0_symbol %>"]
options.salt = "token0"
step = 1

[import.token1]
source = "erc20:0.0.1"
args = ["<%= settings.token1_name %>", "<%= settings.token1_symbol %>"]
options.salt = "token1"
step = 1

[invoke.createPool]
addresses = ["<%= outputs.self.contracts.UniswapV3Factory.address %>"]
abi = "<%= outputs.self.contracts.UniswapV3Factory.abi %>"
func = "createPool"
args = [
  "<%= outputs.token0.contracts.erc20.address %>",
  "<%= outputs.token1.contracts.erc20.address %>",
  500
]
step = 2
