name = "uniswap-v3"
description = "Decentralized trading protocol"
version = "0.0.1"

[setting.salt]
defaultValue = "uniswap"

[setting.token0_name]
defaultValue = "Synthetix USD"

[setting.token0_symbol]
defaultValue = "sUSD"

[setting.token1_name]
defaultValue = "USD Coin"

[setting.token1_symbol]
defaultValue = "USDC"

[setting.pool_fee]
defaultValue = 500

[contract.weth]
artifact = "WETH9"
step = 1

[contract.factory]
artifact = "UniswapV3Factory"
salt = "<%= settings.salt %>"
step = 1

[contract.router]
artifact = "SwapRouter"
salt = "<%= settings.salt %>"
args = [
  "<%= outputs.self.contracts.factory.address %>",
  "<%= outputs.self.contracts.weth.address %>",
]
step = 2

[import.token0]
source = "erc20:0.0.1"
args = ["<%= settings.token0_name %>", "<%= settings.token0_symbol %>"]
options.salt = "token0"
step = 2

[import.token1]
source = "erc20:0.0.1"
args = ["<%= settings.token1_name %>", "<%= settings.token1_symbol %>"]
options.salt = "token1"
step = 2

[invoke.createPool]
addresses = ["<%= outputs.self.contracts.factory.address %>"]
abi = "<%= outputs.self.contracts.factory.abi %>"
func = "createPool"
args = [
  "<%= outputs.token0.contracts.erc20.address %>",
  "<%= outputs.token1.contracts.erc20.address %>",
  <%= settings.pool_fee %>
]
step = 3
