name = "uniswap-v3"
description = "Decentralized trading protocol"
version = "0.0.1"

[setting.salt]
defaultValue = "uniswap"

[setting.token0_address]
[setting.token1_address]

[setting.pool_fee]
defaultValue = 500

[contract.weth]
artifact = "WETH9"
step = 1

[contract.factory]
artifact = "UniswapV3Factory"
salt = "<%= settings.salt %>"
step = 1

[contract.router]
artifact = "SwapRouter"
salt = "<%= settings.salt %>"
args = [
  "<%= outputs.self.contracts.factory.address %>",
  "<%= outputs.self.contracts.weth.address %>",
]
step = 2

[invoke.createPool]
addresses = ["<%= outputs.self.contracts.factory.address %>"]
abi = "<%= outputs.self.contracts.factory.abi %>"
func = "createPool"
args = [
  "<%= settings.token0_address %>",
  "<%= settings.token1_address %>",
  "<%= settings.pool_fee %>"
]
step = 3
